<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encryptedfields.proto

namespace GPBMetadata;

class Encryptedfields
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(
            '
�
encryptedfields.protoEncapsulations"E
EncryptedField
mac (	

iv (
tag (
value (B�Encapsulationsbproto3',
            true
        );

        static::$is_initialized = true;
    }
}
