<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encryptedfields.proto

namespace Encapsulations;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Encapsulations.EncryptedField</code>
 */
class EncryptedField extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string mac = 1;</code>
     */
    protected $mac = '';
    /**
     * Generated from protobuf field <code>bytes iv = 2;</code>
     */
    protected $iv = '';
    /**
     * Generated from protobuf field <code>bytes tag = 3;</code>
     */
    protected $tag = '';
    /**
     * Generated from protobuf field <code>bytes value = 4;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param  array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mac
     *     @type string $iv
     *     @type string $tag
     *     @type string $value
     * }
     */
    public function __construct($data = NULL)
    {
        \GPBMetadata\Encryptedfields::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string mac = 1;</code>
     * @return string
     */
    public function getMac()
    {
        return $this->mac;
    }

    /**
     * Generated from protobuf field <code>string mac = 1;</code>
     * @param  string $var
     * @return $this
     */
    public function setMac($var)
    {
        GPBUtil::checkString($var, True);
        $this->mac = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes iv = 2;</code>
     * @return string
     */
    public function getIv()
    {
        return $this->iv;
    }

    /**
     * Generated from protobuf field <code>bytes iv = 2;</code>
     * @param  string $var
     * @return $this
     */
    public function setIv($var)
    {
        GPBUtil::checkString($var, False);
        $this->iv = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes tag = 3;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Generated from protobuf field <code>bytes tag = 3;</code>
     * @param  string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, False);
        $this->tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes value = 4;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 4;</code>
     * @param  string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }
}
